name: Run Python Script and Deploy HTML to GitHub Pages

on:
  schedule:
    # Runs once every day at midnight UTC
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deployment'
        type: choice
        default: 'manual_update'
        options:
        - testing
        - manual_update

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4



    # Step 4: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 5: Install required dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 6: Run your Python script
    - name: Run Python script
      run: python main.py


    - name: Commit and push cache
      run: |
        git add .
        git commit -m "Cache update $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to cache."
        git push origin main

    # Step 9: Setup Pages
    - name: Setup Pages
      uses: actions/configure-pages@v5

    # Step 10: Upload artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    # Step 11: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
